### ISSUE TITLE
Documentarian should say it requires Janet 1.9

### ISSUE THREAD

**Issue by hinkelman** [pyrmont/documentarian#1]
This is what I get when I clone the repo and run `jpm build` (on Ubuntu 20.04): 

```
generating executable c source...
compile error: unknown symbol sort-by on line 132, column 3 while compiling src/documentarian.janet
compile error: unknown symbol bindings->items on line 180, column 14 while compiling src/documentarian.janet
error: expected integer key in range [0, 5), got nil
  in <anonymous> [/usr/local/bin/jpm] on line 409, column 19
  in do-rule [/usr/local/bin/jpm] on line 90, column 24
  in do-rule [/usr/local/bin/jpm] (tailcall) on line 88, column 44
```

**Comment by pyrmont** [comment]
Oh yeah, sorry. I need to put this in the README but this depends on `sort-by` and that's only been added in 1.9. At this stage, you'll need to build Janet from source to use Documentarian. I'm sorry that wasn't clear! :(

**Comment by hinkelman** [comment]
No problem. I switched to Janet 1.9 and `documentarian` worked liked a charm. Thanks!
