### ISSUE TITLE
native loader not working - for everyone, or just me?

### ISSUE THREAD

**Issue by subsetpark** [pyrmont/documentarian#10]
Not sure where the error is here: in documentarian's build settings or in the void linux janet package.

But running documentarian on a package with a native module produces this error:

```
error: could not load native /usr/lib64/janet/jnj-primitives.so: /usr/lib64/janet/jnj-primitives.so: undefined symbol: janet_buffer_push_cstring
  in native
  in native-loader [boot.janet] on line 2615, column 40
  in require-1 [boot.janet] on line 2638, column 18
  in import* [boot.janet] on line 2669, column 15
  in _thunk [jnj.janet] (tailcall) on line 1, column 1
  in dofile [boot.janet] (tailcall) on line 2607, column 7
  in source-loader [boot.janet] on line 2618, column 15
  in require-1 [boot.janet] (tailcall) on line 2638, column 18
  in extract-env [src/documentarian.janet] on line 355, column 18
  in <anonymous> [src/documentarian.janet] on line 438, column 35
  in reduce [boot.janet] on line 824, column 27
  in generate-doc [src/documentarian.janet] (tailcall) on line 437, column 13
```

I've confirmed that I'm able to import that module from a Janet repl, so it's something particular to how it's being loaded in the documentarian context.

**Comment by pyrmont** [comment]
Is this a private module?

**Comment by subsetpark** [comment]
I don't know exactly what you mean, but when it's installed, it's importable with a normal `(import jnj-primitives)`. So - no, I don't think so?

**Comment by pyrmont** [comment]
Oh, I meant is the code for the module publicly available? I had a quick look using GitHub and Google but couldn't find it.

**Comment by subsetpark** [comment]
ah! you can clone or browse here: https://git.sr.ht/~subsetpark/jnj

**Comment by pyrmont** [comment]
Hmmm. I don't have J installed so building fails but I wonder looking at the stacktrace if the problem isn't occurring because of the difference between `import` and `require`. If you use `require` at the REPL does it work fine?

**Comment by pyrmont** [comment]
The issue is definitely with Documentarian. @sogaiu was kind enough to test it with some other packages that use native libraries and found the problem there, too. I think the issue might be in how I've got the binary of Documentarian building but I'll need to take a closer look.

**Comment by pyrmont** [comment]
@subsetpark I realise this took a very long time but I think Documentarian can now load native modules. I don't know if you still have a reason to use it but if you try it out, let me know if it's working for you. If you're curious, my solution was to add a custom module path that checks the `build/` folder for `.so` objects that match the name given in the `declare-native` form.
