### ISSUE TITLE
Feature idea: specify JANET_PATH on command line

### ISSUE THREAD

**Issue by subsetpark** [pyrmont/documentarian#11]
documentarian always looks for imports in the system janet path. It would be useful to be able to specify `JANET_PATH` as a flag, or have it respect the JANET_PATH env variable, so it could be run on projects whose dependencies are installed in a local tree.

**Comment by subsetpark** [comment]
Here's a reference to how I do the same thing in bagatto: https://git.sr.ht/~subsetpark/bagatto/tree/master/item/src/env.janet#L27

**Comment by pyrmont** [comment]
Yeah, I agree. This support should be added.

**Comment by subsetpark** [comment]
This might be obsoleted by `jpm exec`.

**Comment by pyrmont** [comment]
Well, it took almost two years but I finally added it! You can now set the `syspath` by using the `--syspath` command line option.

**Comment by pyrmont** [comment]
I've changed it to work more like `jpm`. You can now do either `--local` or `--tree <path>`.
