### ISSUE TITLE
Native module problem

### ISSUE THREAD

**Issue by GrayJack** [pyrmont/documentarian#3]
In my purely native module I get the following error:

`error: Project file must contain declare-project and declare-source`

But in native modules only requires `declare-project` and `declare-native` to jpm to accept it

**Comment by pyrmont** [comment]
@GrayJack The files referenced in your `declare-native` map are C files, right? Unfortunately, Documentarian is only intended to work with Janet files.

**Comment by pyrmont** [comment]
@GrayJack It took a few months but I added experimental support for native modules. It's working with Markable ([example](https://github.com/pyrmont/markable/blob/master/api.md)) but I haven't tested it extensively.

I'm not sure if you're still interested in this but if you try it out and notice any problems, please let me know! I'll close for now on the expectation that this works but can always reopen if that's not the case.
