### ISSUE TITLE
error in binding-details

### ISSUE THREAD

**Issue by subsetpark** [pyrmont/documentarian#4]
When running documentarian on [fugue](https://sr.ht/~subsetpark/fugue), I get this traceback:

```
error: expected integer key in range [0, 0), got :ns
  in binding-details [src/documentarian.janet] on line 198, column 29
  in extract-bindings [src/documentarian.janet] on line 278, column 11
  in generate-doc [src/documentarian.janet] (tailcall) on line 427, column 17
```

Lemme know if this rings any bells!

**Comment by subsetpark** [comment]
An interesting trace:

```
trace [src/documentarian.janet]: (ns-or-alias name ns) is "fugue"
trace [src/documentarian.janet] on line 198, column 30: meta is @{:doc "(match x & cases)\n\nPrototype-aware version of `match`. Introduces one new case form:\n\n- `(@ <prototype-name> <dictionary>)`: Will pattern match against an instance\nof `prototype-name`. Additionally, will validate at compile-time that every\nkey in `dictionary` is a field that's present on the specified prototype." :macro true :source-map ("fugue.janet" 877 1) :value <function match>}
trace [src/documentarian.janet]: (ns-or-alias name ns) is "fugue"
trace [src/documentarian.janet] on line 198, column 30: meta is @[]
```

The binding it's throwing up on is `:macro-lints`. That's a new element in Janet; so I guess documentarian needs to be updated; right now it thinks that it's a symbol defined in the fugue source.

Maybe it's as easy as only processing the binding if it's a symbol?

**Comment by pyrmont** [comment]
@subsetpark Thanks for reporting and looking into this. You're right, I'm not familiar with the `:macro-lints` change. I'll have to have a look at what's changed in Janet.

**Comment by pyrmont** [comment]
Oh, and thanks for submitting PR #5! I want to understand the problem better but hopefully that's the fix (less code for me to write! :P).

**Comment by saikyun** [comment]
I got the same error when trying to run on the testament library.
