### ISSUE TITLE
Inconsistency in markdown generation between project and definition docstrings

### ISSUE THREAD

**Issue by subsetpark** [pyrmont/documentarian#6]
This one is kind of a bother to unit-test. 

I'll use quotation marks as an example:

If a function definition has quotation marks within a code fence:

````
Example prose, followed by code:

```
(example-fun "argument")
```
````

Then documentarian will do the right thing and reproduce the code block verbatim in the markdown output.

However, if that same text is found in the doc section in a `project.janet`, documentarian will convert the quotation marks to html entities, thus breaking the ultimate rendering of the code block:

````
Example prose, followed by code:

```
(example-fun &quote;argument&quote;)
```
````

**Comment by pyrmont** [comment]
I was having a quick look at the template and we're using Mustache's escaping functionality (`&`) with `docstring` but not with `doc`:

https://github.com/pyrmont/documentarian/blob/a31bcf5f4aab9ecfe8349e1a362b73cfd91ba225/src/documentarian.janet#L47-L81

Could that be the cause of the problem?

**Comment by subsetpark** [comment]
Certainly sounds like it lines up. I’ll see if I can get a test case worked up.
